name: Build and Deploy to Alwaysdata

on:
  push:
    branches:
      - main  # hoặc master tùy branch của bạn

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Binary for Linux
        run: |
          go env -w GOPROXY=https://goproxy.io,direct
          go mod tidy
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o server_app ./cmd/server/main.go
          chmod +x server_app

      - name: Deploy Binary via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "server_app,web/templates,web/static"
          target: "/home/${{ secrets.SSH_USER }}/app-file"

      - name: Restart Site via Alwaysdata API
        run: |
          curl -X POST \
            -u "${{ secrets.ALWAYSDATA_API_TOKEN }}:" \
            https://api.alwaysdata.com/v1/site/1076022/restart/
